### PR TITLE
Fix SPM unsupported package layout issue by excluding the test directory.

### PR DESCRIPTION
**Pull request by rayfix**
> swift build

    error: the package has an unsupported layout, unexpected source file(s) found: /Packages/Wrap-2.0.1/Tests/WrapTests.swift

Just as was done with the Unbox project, add Tests to the package exclude list in the Package.swift manifest file.

### CODE REVIEW

**Review by JohnSundell — APPROVED** [review]
Sweet 🚀

**Comment by JohnSundell** [comment]
@rayfix Thanks for this fix 👍 Will make a release later tonight so that SPM can again be used 😄

**Comment by JohnSundell** [comment]
@rayfix Released! https://github.com/JohnSundell/Wrap/releases/tag/2.0.2 🚀

**Comment by neonichu** [comment]
This is not such a good idea, because it breaks `swift test`. The better way to do this is to create modules for your tests, see <https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#test-suite-layouts> or look at the structure `swift package init` creates for an example.

**Comment by rayfix** [comment]
Thanks @neonichu.  You are correct!  Since this was my first foray into SPM, I didn't appreciate it at the time that I was making the fix.  (It just mirrors the way Unbox works!)  I will open a new issue and can make the fix soon.

**Pull request merged**
